services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-CU25-ubuntu-22.04
    container_name: sqlserver
    restart: unless-stopped
    ports:
      - "1433:1433"
    env_file:
      - .env
    environment:
      ACCEPT_EULA: ${ACCEPT_EULA}
      MSSQL_SA_PASSWORD: ${MSSQL_SA_PASSWORD}
      MSSQL_PID: ${MSSQL_PID}
    volumes:
      - /home/docker-data/sqlserver:/var/opt/mssql
    networks:
      - home-network
    healthcheck:
      test:
        [
          "CMD",
          "/opt/mssql-tools18/bin/sqlcmd",
          "-S",
          "localhost",
          "-U",
          "healthcheck_user",
          "-P",
          "${HEALTHCHECK_PASSWORD}",
          "-C",
          "-Q",
          "SELECT 1",
        ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    deploy:
      resources:
        limits:
          memory: 8g
        reservations:
          memory: 512m

networks:
  home-network:
    external: true
