[EULA]
accepteula = Y

[sqlagent]
enabled = true

[memory]
memorylimitmb = 5632

[network]
forceencryption = 0
tlsprotocols = 1.2

[telemetry]
customerfeedback = false

[filelocation]
defaultdatadir = /data/db
defaultlogdir  = /data/log
defaultbackupdir = /data/backup
defaultdumpdir = /data/dump
